
def gitRepoUrl = 'https://github.com/chauhanvikas45/food.git'
def serviceName = 'food'

node {
  stage('Build App') {
    checkout scm
    sudo sh "./gradlew clean build --no-daemon"
  }

  stage('UnitTest App') {
    checkout scm
    sudo sh "./gradlew test  --no-daemon"
  }


}

